### ISSUE TITLE
Doppelte HTML, HEAD und BODY Tags

### ISSUE THREAD

**Issue by itgi** [WebentwicklerAt/typo3-emogrifier#1]
Die HTML Tags "HTML, HEAD und BODY" werden durch Emogrifier doppelt hinzugefügt. Das ist für eine saubere HTML Validierung nicht so schön. 

Ein Workaround wäre das HTML im Emogrifier so zu laden:
`$xmlDocument->loadHTML(mb_convert_encoding($this->html, 'HTML-ENTITIES', 'UTF-8'), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);`

Dadurch werden die doppelten Tags verhindert, aber ist keine saubere Lösung.

**Comment by RoyalKnight** [comment]
Sorry for the late reply, I did not get/see notification for it.
You have to set `config.disableAllHeaderCode = 1` for your `PAGE`.
