### ISSUE TITLE
Core Security Fix breaks Emogrifier

### ISSUE THREAD

**Issue by dvoigt** [WebentwicklerAt/typo3-emogrifier#11]
Calling postUserFunc = WebentwicklerAt\Emogrifier\UserFunctions\Emogrifier->emogrify on TYPO3 Core 7.6.30+ throws exception  #1530103999: Method stream_select() cannot be used which can be traced back to this piece of code:

https://git.higidi.com/TYPO3/TYPO3.CMS/commit/28e9420acb5cec66ae929d8390129ebad7dbe891

**Comment by leitgab** [comment]
This is an issue of TYPO3/phar-stream-wrapper#19

**Comment by oliverklee** [comment]
For my `phpunit` and `seminars` extensions, I've moved away from using a phar for included libraries due to this problem: https://github.com/oliverklee/ext-phpunit/pull/87

**Comment by leitgab** [comment]
Composer based installations are standard nowadays, therefore I dropped support of non-composer installations and no phar-file is included any more.
