### ISSUE TITLE
Compatibility with TYPO3 v9 LTS (9.5)

### ISSUE THREAD

**Issue by luberti** [WebentwicklerAt/typo3-emogrifier#12]
Are there plan for upgrading emogrifier to be TYPO3 9 compatible? Is there a timin.
If Iwould like tocontribute how I should proceed:  againt s wich branch should I pull requests?

**Comment by oliverschloebe** [comment]
Any news on this?

**Comment by leitgab** [comment]
Removed support of TYPO3 7 LTS and add support for TYPO3 9 LTS in released version 3.0.0.
