### ISSUE TITLE
composer.json contains outdated typo3/cms package requirement

### ISSUE THREAD

**Issue by mediaessenz** [WebentwicklerAt/typo3-emogrifier#14]
Because of this outdated requirement, all installations who require "webentwicklerat/emogrifier" will **not** use the correct package "typo3/cms-core" anymore.

**Comment by leitgab** [comment]
Removed support of TYPO3 7 LTS and add support for TYPO3 9 LTS in released version 3.0.0. Require constraint was updated with version change.
