### ISSUE TITLE
Make extension TYPO3 11 compatible

### ISSUE THREAD

**Issue by mediaessenz** [WebentwicklerAt/typo3-emogrifier#18]
The current (development) version is not working under TYPO3.

I wil create a PR to do so.

**Comment by abvdveen** [comment]
Locally I also added the FILE ContentObject from Typo3 9 to the ext, to prevent the error "Class 'CONTENT' not found", when including the css file within the EMOGRIFIER object with a FILE object - see #17.

Or do you have a better solution for this?

**Comment by mediaessenz** [comment]
I use FLUIDTEMPLATE for both cases.

```
page = PAGE
page {
	typeNum = 0
	config {
		disableAllHeaderCode = 1
		admPanel = 0
		xhtml_cleaning = 0
	}
	10 = EMOGRIFIER
	10 {
		extractContent = 1
		css = COA
		css {
			10 = FLUIDTEMPLATE
			10.file = EXT:theme/Resources/Public/Css/newsletter.css
		}
		html = FLUIDTEMPLATE
		html.file = EXT:theme/Resources/Private/Extensions/BootstrapPackage/Templates/Page/Newsletter.html
	}
}
```

**Comment by abvdveen** [comment]
Ok, thanks. Because oliverschloebe mentioned in #17 'While this might be working for the template files it still does not for the CSS files.' I hadn't tried that myself.

**Comment by leitgab** [comment]
[v5](https://github.com/WebentwicklerAt/typo3-emogrifier/tree/v5) and [v6](https://github.com/WebentwicklerAt/typo3-emogrifier/tree/v6) branches, as well as their related tags do support TYPO3 11.
