### ISSUE TITLE
Bug: Settings.yml should be named Settings.cfg

### ISSUE THREAD

**Issue by marble** [WebentwicklerAt/typo3-emogrifier#3]
The documentation isn't rendered at docs.typo3.org because the settings file cannot be read. It has *.ini-style content - which is very good and what we expect nowadays. But the name is wrong. Since it's treated as a Yaml file it cannot be read. Please rename the file to 'Settings.cfg' and try again!

If you are on Linux or Mac and you have Docker you probably want to read https://github.com/t3docs/docker-render-documentation That image is working!

**Comment by RoyalKnight** [comment]
New version with updated `Settings.cfg` released.

**Comment by marble** [comment]
Very nice: https://docs.typo3.org/typo3cms/extensions/emogrifier/1.1.1/ 
And there aren't even warnings. Congratulations and - thank you!
See the 'BUILDINFO' in the 'Related Links'
![151](https://user-images.githubusercontent.com/307057/30783838-fed841a4-a149-11e7-96ee-3ebab4adcbff.png)
