### ISSUE TITLE
Set doctype, viewport and other header data

### ISSUE THREAD

**Issue by dvoigt** [WebentwicklerAt/typo3-emogrifier#5]
Doctype is hardcoded in _Resources/Private/PHP/emogrifier/Classes/Emogrifier.php_ to  `<!DOCTYPE html>`

I want to change it to xhtml_transitional. 

In order to not have double head and body tags, all header code is disabled setting _page.config.disableAllHeaderCode = 1_ as described in issue #1 

So now there's no documented way of setting it. 
Same problem with meta.viewport: if header code is disabled, there doesn't seem to be a way to set it.

**Comment by oliverklee** [comment]
Hi @dvoigt, one of the maintainers of the Emogrifier project here. :-)

Emogrifier does not add a second set of `HEAD` or `BODY` tags. So it looks like this is not a bug in the Emogrifier library, but either in this extension of the TYPO3 configuration. 

Emogrifier will keep the document type you've provided. The HTML5 document type is only added if there is not document type yet: https://github.com/MyIntervals/emogrifier/blob/master/src/Emogrifier.php#L1503

Also, Emogrifier keeps the `meta.viewport` etc.

So my recommendation is not to make those things configurable for Emogrifier, but instead solve the problem of double `HEAD` and `BODY` tags (on the TYPO3 side).

**Comment by dvoigt** [comment]
Hi @oliverklee, thank you. I agree, it's either the implementation into TYPO3, or maybe just lack of documentation. In that case, this should be closed and the discussion continued in #6

**Comment by RoyalKnight** [comment]
Emogrifier requires two strings for the processing: HTML and CSS. If the HTML does not contain a html tag (and/or some other tags) those are added automatically by the library - as you have noticed.

So the straight-forward solution would be, to use the PAGE content object as HTML source:
```
[...]
page.10 = EMOGRIFIER
page.10.html = PAGE
[...]
```
Unfortunately the PAGE content object can be used on the uppermost level only.

I have a local version, which adds some additional options. My local development version adds an option `extractContent`, which returns the content from within the body tags only. Furthermore some other stuff (user function, view helper, library update to 2.0) is included. What's missing for the release of this version is documentation. I plan to release the new version with upgraded documentation during the next days (maybe today/tomorrow). Stay tuned!
