### ISSUE TITLE
Task: Add examples to documentation

### ISSUE THREAD

**Issue by dvoigt** [WebentwicklerAt/typo3-emogrifier#6]
I got the extension to work with my site based on TYPO3/fluidpages, but it's not well documented in the manual. I'd suggest adding an example for different scenarios.
This one worked for me, although there are some issues:

# Disable all header code
page.config.disableAllHeaderCode = 1

# Disable default fluid rendering
page.5 >

# Invoke Emogrifier
page.10 = EMOGRIFIER

# CSS from file
page.10.css = COA
page.10.css.10 = FILE
page.10.css.10.file = EXT:myext/Resources/Public/css/styles.css

# HTML from Fluidpages
page.10.html = USER
page.10.html.userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
page.10.html.extensionName = Fluidpages
page.10.html.vendorName = FluidTYPO3
page.10.html.pluginName = Page

**Comment by RoyalKnight** [comment]
Just updated the documentation with more examples included.

**Comment by dvoigt** [comment]
Thank you! 
If you want to make life really easy for users of [EXT:fluidpages](https://github.com/FluidTYPO3/fluidpages) (and not just "fluid pages") you can include this example (works for me).

10.html = USER
10.html.userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
10.html.extensionName = Fluidpages
10.html.vendorName = FluidTYPO3
10.html.pluginName = Page
